---
- name: Linux Health Check
  hosts: all
  tasks:
    - name: Ping my hosts
      ansible.builtin.ping:

    - name: Disk free space
      assert:
        that:
          - mount.size_available > mount.size_total|float * 0.25
        fail_msg: Disk space on {{ mount }} has reached 75% threshold
        success_msg: "Disk space on {{ mount }} is less than 75%"
        quiet: true
      vars:
        mount: "{{ ansible_mounts | selectattr('mount','equalto',item.mount) | list | first }}"
      with_items:
        - "{{ ansible_mounts }}"
      ignore_errors: true

    - name: Memory usage
      assert:
        that:
          - ansible_memory_mb.nocache.used < ansible_memtotal_mb|float * 0.75
        fail_msg: "Memory usage is over 75%"
        success_msg: "Memory usage is under 75%"
      ignore_errors: true

    - name: Swap
      assert:
        that:
          - ansible_memory_mb.swap.used > ansible_memory_mb.swap.total|float * 0.25
        fail_msg: "Swap usage is over 25%"
        success_msg: "Swap usage is under 25%"
      ignore_errors: true

    - name: Load average
      assert:
        that:
          - ansible_loadavg['15m'] / ansible_processor_cores < 1
        fail_msg: "Load average is greater than 1 per CPU core"
        success_msg: "Load average is less than 1 per CPU core"
      ignore_errors: true
